[package]
name = "rsgl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bytemuck = "1.21.0"
env_logger = "0.11.6"
fs_extra = "1.3.0"
glam = "0.29.2"
glob = "0.3.2"
image = "0.25.5"
log = "0.4.22"
pollster = "0.4.0"
tobj = "4.0.3"
wgpu = "24.0.1"
winit = "0.30.8"
